#jdbc数据源
spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/2springboot_study_house?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  ai:
    openai:
          # 这里换成你刚刚申请的 DeepSeek API Key
          api-key: sk-6cb6a8839bd54a5eafd8762b28bfc12e
          # 将官方地址替换为 DeepSeek 的地址
          base-url: https://api.deepseek.com
          chat:
            options:
              # 使用 DeepSeek 的模型
              model: deepseek-chat

#扫描mapper配置User
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)


server:
  port : 8087

#设置统一的主键生成策略

